import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BsGrid3X3GapFill } from 'react-icons/bs';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Neyran Melo portfolio
        </h1>

        <p className={styles.description}>
          Front-end developer{''}
          <code className={styles.code}>javascript(node,react e next)</code>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/neyranms" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Projetos concluídos, em andamento ou travando com erros desconhecidos pela humanidade. </p>
          </a>

          <a href="https://www.linkedin.com/in/neyran-melo-766036163/" className={styles.card}>
            <h2>Linkedin &rarr;</h2>
            <p>Contato profissional aberto para novas oportunidades nesse Mundo, Marte e Lua.</p>
          </a>

          <a
            href="https://discord.gg/xx5XDKkDQg"
            className={styles.card}
          >
            <h2>Discord &rarr;</h2>
              email: neyran22@gmail.com\n
              cel: +55 11 9 8284-6109

              <textarea id="ta" style="height: 100px">
              </textarea>

              <div id="dv"></div>
          </a>

          <a
            href="https://linktr.ee/neyranx"
            className={styles.card}
          >
            <h2>Socialmedias &rarr;</h2>
            <p>
              vídeos, fotos, edições e transmissões enviadas em plataformas web.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
