import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Neyran Melo portfolio<a href="https://static-cdn.jtvnw.net/jtv_user_pictures/ea97be0c-5c76-4938-8680-ac6dd21b5d39-profile_image-300x300.png">?</a>
        </h1>

        <p className={styles.description}>
          Frontend developer{''}
          <code className={styles.code}>js(node,react e next)</code>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/neyranms" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Projetos em andamento, concluídos com sucesso ou travando com erros desconhecidos pela humanidade. </p>
          </a>

          <a href="https://www.linkedin.com/in/neyran-melo-766036163/" className={styles.card}>
            <h2>Linkedin &rarr;</h2>
            <p>Contato profissional aberto para novas oportunidades nesse Mundo, Marte e na Lua.</p>
          </a>

          <a
            href="https://discord.gg/xx5XDKkDQg"
            className={styles.card}
          >
            <h2>Discord &rarr;</h2>
            <p>email: neyran22@gmail.com
              cel: +55 11 9 8284-6109
            </p>
          </a>

          <a
            href="https://linktr.ee/neyranx"
            className={styles.card}
          >
            <h2>Socialmedias &rarr;</h2>
            <p>
              vídeos, fotos, edições e transmissões enviadas em plataformas web.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
